version: '3' 

services:  
  tokensTool:  
    # 该服务使用的 Docker 镜像
    image: yangclivia/gpt4-copilot-java:latest  
    # Java 的环境变量 （可适当调节，用copilot可以适当调大点，具体可问gpt了解）
    environment:  
      - JAVA_OPTS=-XX:+UseParallelGC -Xms128m -Xmx128m -XX:MaxMetaspaceSize=128m  
    # 为该服务创建的容器的名称
    container_name: gpt4-copilot-java
    # 容器总是重新启动
    restart: always  
    # 容器运行的用户
    user: root  
    # 容器的网络模式
    network_mode: host  
    pid: host  
    privileged: true  
    command:  
      - --log=info
      - --server.port=8081 
      #自定义前缀
      - --server.servlet.context-path=/

